### ISSUE TITLE
apostrophe and quotes

### ISSUE THREAD

**Issue by LorenzoScarpa** [zorro-del-caribe/ship-hold#11]
if you wants to insert or update a record with an apostrophe the query builder return a syntax error

> sh: 2.0.1
> pg: 10

> Bug

**Comment by lorenzofox3** [comment]
can you please provide some snippet to make sure we are talking about the same thing ?

A workaround would be to use parameterized query:

```Javascript
import { insert } from "https://unpkg.com/ship-hold-querybuilder@2.0.0/dist/bundle/module.js";
insert({
  foo: '$foo'
})
  .into("table")
  .build({
      foo:`b'ar`
  });
```

see [codepen](https://codepen.io/lorenzofox3/pen/OeKvgL?editors=1111)

**Comment by lorenzofox3** [comment]
actually I think you can also escape the character

```Javascript
insert({foo:'b\'ar')
.build()
```

**Comment by LorenzoScarpa** [comment]
i have fixed, using parameterized query. Thank you very much.
