### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Jonathan-Navagis** [zorro-del-caribe/ship-hold#12]
When using ship-hold ^2.0.1, the documentation says that you can refer to a connection host string with "hostname" in reality it should be referred to by "host".

Example:
https://ship-hold.com/index.html#initialisation

``` 
const {shiphold} = require('ship-hold');
const sh = shiphold({
    hostname: '127.0.0.1',
    user: 'docker',
    password: 'docker',
    database: 'dev'
});
```
My code that worked:

```
const sh = shiphold({
    host: conf.database.hostname,
    user: conf.database.user,
    password: conf.database.password,
    database: conf.database.database
});
```

I think it's a slight error in the documentation maybe? I'm not sure but I spent a good twenty minutes trying to figure it out before it hit me in the face.

**Comment by lorenzofox3** [comment]
Thanks for the feedback
