### ISSUE TITLE
Typescript types don't know about run method of builder's

### ISSUE THREAD

**Issue by breathe** [zorro-del-caribe/ship-hold#15]
```
sh.select().run() // <-- run method on type declaration

sh.select().from("table").run() // <-- run method not on type declaration
```

**Comment by lorenzofox3** [comment]
Thanks @breathe 

Can you give me more details: 

I have the following code
```typescript
import {shiphold} from 'ship-hold';

const sh = shiphold({
    host: '127.0.0.1',
    user: 'docker',
    password: 'docker',
    database: 'dev'
});

sh.select().run();
sh.select().from('foo').run();
```

with the following tsconfig
```JSON
{
  "compilerOptions": {
    "lib": [
      "es2018"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "preserveConstEnums": true,
    "target": "es2018"
  }
}
```

which compiles to 

```Javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ship_hold_1 = require("ship-hold");
const sh = ship_hold_1.shiphold({
    host: '127.0.0.1',
    user: 'docker',
    password: 'docker',
    database: 'dev'
});
sh.select().run();
sh.select().from('foo').run();
```

with no issue/warning 

typescript version is ^3.6.2

I think type definition can be improved though now that the "this type" is supported for polymorphism. Need to check though cause ship hold query builders are built as mixins

**Comment by breathe** [comment]
Hi @lorenzofox3 -- the noImplicitAny option is the issue.  The latest published build actually doesn't use the type definitions at all because of the (just fixed) typo in package.json.  Because there is no type definition available for the 'ship-hold' module and because you have 'noImplictAny' inference disabled -- typescript is inferring the any type for shiphold -- which means there's no type-checking happening in above code at all.  

If you set 'noImplicitAny: true' -- you will see a type-checking error on the `import {shiphold} from "ship-hold"` because the types aren't found.  

![image](https://user-images.githubusercontent.com/434034/64554621-04290e80-d2f9-11e9-92f0-b00ebfc04982.png)

When you fix that (`yarn add https://github.com/zorro-del-caribe/ship-hold.git` to get the version of package from github repo with the fix) you'll then see that the .run() method isn't available on the type returned from .from()

![image](https://user-images.githubusercontent.com/434034/64554579-ee1b4e00-d2f8-11e9-8b93-2405fc8abcda.png).

noImplicitAny: true is a _very_ bad idea - its a terrible default and really needs to have its default value changed in the compiler ...  That setting drastically reduces the utility of typescript and also makes it significantly harder to learn the language or understand it due to reasons exactly like this one.  When the type inference system infer's the any type somewhere you don't expect, all bets are off in terms of being able to understand the effect of changes to existing types on a codebase -- its pretty easy to get from noImplicitAny: true to noImplicitAny:false -- you can usually just explicitly add the any type to the places that its needed -- I don't think ship-hold should need it anywhere -- probably suffices to just have ServiceBuilder extend WithQueryRunner ...?

**Comment by lorenzofox3** [comment]
oh you are right ! let me review it

**Comment by lorenzofox3** [comment]
type definitions are not perfect (they could be more precise but would require a lot of work to more or less mirror SQL grammar...)

But it should be a good start. Let me know if you have other issues
