### ISSUE TITLE
Ship-fold query builder for browser

### ISSUE THREAD

**Issue by ansarizafar** [zorro-del-caribe/ship-hold#9]
Thanks for this amazing lib. I want to know, Is it somehow possible to extract only query builder as a separate package for use on client side in browser/electron/ionic app. In my use case I want to build query on the client and than send it to a nodejs endpoint for execution.

**Comment by lorenzofox3** [comment]
sure. ``npm install ship-hold-querybuilder`` and [repo](https://github.com/zorro-del-caribe/ship-hold-querybuilder). You don't have the services and builder inclusions though
